from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import os
import time
import psutil  # <== nouveau

SELENIUM_PROFILE_DIR = os.path.abspath("chrome_selenium_profile")
COOKIE_FILE = "cookie.txt"

EDIT_THIS_COOKIE_HEADER = """// Semicolon separated Cookie File
// This file was generated by EditThisCookie
// Details: http://www.ietf.org/rfc/rfc2109.txt
// Example: http://www.tutorialspoint.com/javascript/javascript_cookies.htm"""

def main():
    print("🚀 Lancement de Chrome avec profil Selenium dédié...")

    # 🔒 Fermer les processus Chrome liés à notre profil
    for proc in psutil.process_iter(["pid", "name", "cmdline"]):
        try:
            if "chrome" in proc.info["name"].lower():
                if any("chrome_selenium_profile" in str(arg) for arg in proc.info["cmdline"]):
                    print(f"🧹 Fermeture de Chrome PID {proc.info['pid']}")
                    proc.terminate()
        except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
            pass

    options = Options()
    options.add_argument(f"user-data-dir={SELENIUM_PROFILE_DIR}")
    options.add_argument("--start-minimized")
    options.add_argument("--window-position=3000,3000")
    options.add_experimental_option("detach", True)

    driver = webdriver.Chrome(options=options)

    print("🔗 Ouverture de https://www.icloud.com/settings/")
    driver.get("https://www.icloud.com/settings/")
    time.sleep(10)

    print("🍪 Récupération des cookies...")
    cookies = driver.get_cookies()

    if not cookies:
        print("[⚠️] Aucun cookie récupéré.")
        return

    # Génération de la ligne de cookies sans double guillemets internes
    cookie_line = ";".join(
        f'{cookie["name"]}="{cookie["value"].replace(chr(34), "").strip()}"'
        for cookie in cookies
    ) + ";"

    with open(COOKIE_FILE, "w", encoding="utf-8") as f:
        # Pas de ligne vide après le header !
        f.write(EDIT_THIS_COOKIE_HEADER + "\n" + cookie_line)

    print(f"[✅] {len(cookies)} cookies exportés dans {COOKIE_FILE}")
    print("🎯 Format corrigé : prêt pour ton script iCloud (HideMyEmail) ✅")

if __name__ == "__main__":
    main()
