#!/usr/bin/env python3
"""Lance ce script APRÈS t'être connecté sur iCloud dans Chrome."""
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import os, sys

BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
PROFILE_DIR = os.path.join(BASE_DIR, "chrome_selenium_profile")
COOKIE_FILE = os.path.join(BASE_DIR, "cookie.txt")

HEADER = "// Semicolon separated Cookie File\n// This file was generated by EditThisCookie"

opts = Options()
opts.add_argument(f"user-data-dir={PROFILE_DIR}")
opts.add_argument("--headless=new")   # pas besoin de fenêtre
driver = webdriver.Chrome(options=opts)
driver.get("https://www.icloud.com/settings/")

import time; time.sleep(4)
cookies = driver.get_cookies()
driver.quit()

if not cookies:
    print("❌ Aucun cookie — assure-toi d'être connecté à iCloud dans Chrome.")
    sys.exit(1)

line = ";".join(f'{c["name"]}="{c["value"].replace(chr(34),"").strip()}"' for c in cookies) + ";"
with open(COOKIE_FILE, "w") as f:
    f.write(HEADER + "\n" + line)

print(f"✅ {len(cookies)} cookies sauvegardés dans cookie.txt")
print("Lance maintenant : python3 run.py generate")
