#!/usr/bin/env python3
"""
grab_cookie_from_chrome.py
Extrait automatiquement les cookies iCloud depuis Chrome (Profile 1)
et les sauvegarde dans cookie.txt — prêt pour la génération HME.

Usage : python3 grab_cookie_from_chrome.py
"""
import browser_cookie3
import os, sys

BASE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(BASE, "cookie.txt")
HEADER = "// Semicolon separated Cookie File\n// This file was generated by EditThisCookie"

CHROME_PROFILES = [
    "Profile 1", "Profile 2", "Profile 3", "Default"
]

def main():
    print("🔍 Recherche des cookies iCloud dans Chrome…")
    chrome_base = os.path.expanduser("~/Library/Application Support/Google/Chrome")

    cookies = []
    used_profile = None
    for profile in CHROME_PROFILES:
        cookie_db = os.path.join(chrome_base, profile, "Cookies")
        if not os.path.exists(cookie_db):
            continue
        try:
            jar = browser_cookie3.chrome(domain_name=".icloud.com", cookie_file=cookie_db)
            found = list(jar)
            if found:
                cookies = found
                used_profile = profile
                break
        except Exception as e:
            print(f"  ⚠ {profile} : {e}")

    if not cookies:
        print("❌ Aucun cookie iCloud trouvé — assure-toi d'être connecté sur icloud.com dans Chrome")
        sys.exit(1)

    parts = [f'{c.name}="{c.value.replace(chr(34),"").strip()}"' for c in cookies]
    cookie_line = ";".join(parts) + ";"

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(HEADER + "\n" + cookie_line)

    print(f"✅ {len(cookies)} cookies extraits depuis [{used_profile}] → cookie.txt")
    print(f"📁 {OUTPUT}")

if __name__ == "__main__":
    main()
