#!/usr/bin/env python3
"""
GrabDiscount — Générateur d'emails iCloud Hide My Email
========================================================
Usage:
  python3 run.py login     → Ouvre Chrome pour se connecter à iCloud
  python3 run.py generate  → Génère des emails (demande combien)
  python3 run.py list      → Liste tous les emails générés
  python3 run.py export    → Exporte emails.txt en tableau propre
"""

import asyncio, os, sys, json, time, datetime, re
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)
COOKIE_FILE  = os.path.join(BASE_DIR, "cookie.txt")
EMAILS_FILE  = os.path.join(BASE_DIR, "emails.txt")
EXPORT_FILE  = os.path.join(BASE_DIR, "emails_export.txt")

EDIT_COOKIE_HEADER = """// Semicolon separated Cookie File\n// This file was generated by EditThisCookie"""

# ─────────────────────────────────────────
#  SELENIUM — LOGIN + COOKIE EXTRACTION
# ─────────────────────────────────────────
PROFILE_DIR = os.path.join(BASE_DIR, "chrome_selenium_profile")

def get_driver(headless=False):
    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options
    opts = Options()
    opts.add_argument(f"user-data-dir={PROFILE_DIR}")
    opts.add_experimental_option("detach", True)
    if headless:
        opts.add_argument("--headless=new")
    return webdriver.Chrome(options=opts)

def cmd_login():
    """Ouvre Chrome sur iCloud.com/settings pour connexion manuelle."""
    print("\n🌐 Ouverture de Chrome — connectez-vous à iCloud puis appuyez Entrée ici.\n")
    driver = get_driver(headless=False)
    driver.get("https://www.icloud.com/settings/")
    input("   ✅ Une fois connecté sur iCloud, appuyez sur Entrée pour extraire les cookies : ")

    cookies = driver.get_cookies()
    if not cookies:
        print("❌ Aucun cookie récupéré. Assurez-vous d'être bien connecté à iCloud.")
        driver.quit()
        return

    cookie_line = ";".join(
        f'{c["name"]}="{c["value"].replace(chr(34), "").strip()}"'
        for c in cookies
    ) + ";"

    with open(COOKIE_FILE, "w", encoding="utf-8") as f:
        f.write(EDIT_COOKIE_HEADER + "\n" + cookie_line)

    print(f"✅ {len(cookies)} cookies sauvegardés dans cookie.txt")
    driver.quit()

# ─────────────────────────────────────────
#  iCLOUD API
# ─────────────────────────────────────────
def load_cookies() -> str:
    if not os.path.exists(COOKIE_FILE):
        print("❌ cookie.txt introuvable. Lancez d'abord : python3 run.py login")
        sys.exit(1)
    with open(COOKIE_FILE, "r") as f:
        lines = [l for l in f.read().splitlines() if not l.startswith("//") and l.strip()]
    if not lines:
        print("❌ cookie.txt vide. Lancez d'abord : python3 run.py login")
        sys.exit(1)
    return lines[0]

import aiohttp, ssl, certifi

class ICloudHME:
    base_v1 = "https://p68-maildomainws.icloud.com/v1/hme"
    base_v2 = "https://p68-maildomainws.icloud.com/v2/hme"
    params   = {"clientBuildNumber":"2413Project28","clientMasteringNumber":"2413B20","clientId":"","dsid":""}

    def __init__(self, cookies: str):
        self.cookies = cookies.strip()

    async def __aenter__(self):
        ssl_ctx   = ssl.create_default_context(cafile=certifi.where())
        connector = aiohttp.TCPConnector(ssl_context=ssl_ctx)
        self.session = aiohttp.ClientSession(
            headers={
                "User-Agent":    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/123 Safari/537.36",
                "Content-Type":  "text/plain",
                "Accept":        "*/*",
                "Origin":        "https://www.icloud.com",
                "Referer":       "https://www.icloud.com/",
                "Cookie":        self.cookies,
            },
            timeout=aiohttp.ClientTimeout(total=15),
            connector=connector,
        )
        return self

    async def __aexit__(self, *_):
        await self.session.close()

    async def generate_one(self) -> str | None:
        try:
            async with self.session.post(f"{self.base_v1}/generate", params=self.params, json={"langCode":"en-us"}) as r:
                data = await r.json()
        except Exception as e:
            print(f"  ⚠ generate error: {e}")
            return None
        if not data.get("success"):
            reason = (data.get("error") or {}).get("errorMessage") or data.get("reason","?")
            print(f"  ⚠ generate failed: {reason}")
            return None
        email = data["result"]["hme"]
        # Reserve
        try:
            async with self.session.post(f"{self.base_v1}/reserve", params=self.params,
                json={"hme": email, "label": "GrabDiscount", "note": "Auto-generated"}) as r:
                res = await r.json()
        except Exception as e:
            print(f"  ⚠ reserve error for {email}: {e}")
            return None
        if not res.get("success"):
            reason = (res.get("error") or {}).get("errorMessage") or res.get("reason","?")
            print(f"  ⚠ reserve failed for {email}: {reason}")
            return None
        return email

    async def generate_batch(self, n: int) -> list[str]:
        results = await asyncio.gather(*[self.generate_one() for _ in range(min(n,10))])
        return [r for r in results if r]

    async def list_all(self) -> list[dict]:
        try:
            async with self.session.get(f"{self.base_v2}/list", params=self.params) as r:
                data = await r.json()
        except Exception as e:
            print(f"  ⚠ list error: {e}")
            return []
        if not data.get("success"):
            print(f"  ⚠ list failed: {data}")
            return []
        return data.get("result", {}).get("hmeEmails", [])

# ─────────────────────────────────────────
#  COMMANDES
# ─────────────────────────────────────────
async def cmd_generate():
    cookies = load_cookies()
    try:
        n = int(input("\n📧 Combien d'emails à générer ? (max 25 recommandé) : ").strip())
    except ValueError:
        n = 5

    all_emails = []
    async with ICloudHME(cookies) as hme:
        generated = 0
        while generated < n:
            batch = min(n - generated, 10)
            print(f"\n  Génération batch {generated+1}–{generated+batch}...")
            emails = await hme.generate_batch(batch)
            for e in emails:
                print(f"  ✅ {e}")
            all_emails.extend(emails)
            generated += batch
            if generated < n:
                print(f"  ⏳ Pause 5s (limite API Apple)...")
                await asyncio.sleep(5)

    if all_emails:
        with open(EMAILS_FILE, "a", encoding="utf-8") as f:
            f.write("\n".join(all_emails) + "\n")
        print(f"\n✅ {len(all_emails)} emails sauvegardés dans emails.txt")
    else:
        print("\n❌ Aucun email généré. Vérifiez cookie.txt (relancez : python3 run.py login)")

async def cmd_list():
    cookies = load_cookies()
    async with ICloudHME(cookies) as hme:
        emails = await hme.list_all()

    if not emails:
        print("Aucun email trouvé (ou session expirée).")
        return

    active   = [e for e in emails if e.get("isActive")]
    inactive = [e for e in emails if not e.get("isActive")]

    print(f"\n{'─'*62}")
    print(f"  📧  {len(active)} emails actifs   |   {len(inactive)} désactivés")
    print(f"{'─'*62}")
    print(f"  {'EMAIL':<38} {'CRÉÉ LE':<18}")
    print(f"{'─'*62}")
    for e in active:
        ts = datetime.datetime.fromtimestamp(e.get("createTimestamp",0)/1000).strftime("%d/%m/%Y %H:%M")
        print(f"  {e['hme']:<38} {ts}")
    print(f"{'─'*62}\n")

    # Sauvegarde aussi dans emails_export.txt
    with open(EXPORT_FILE, "w", encoding="utf-8") as f:
        f.write(f"# Export iCloud Hide My Email — {datetime.datetime.now():%d/%m/%Y %H:%M}\n")
        f.write(f"# {len(active)} emails actifs\n\n")
        for e in active:
            ts = datetime.datetime.fromtimestamp(e.get("createTimestamp",0)/1000).strftime("%d/%m/%Y %H:%M")
            f.write(f"{e['hme']}  (créé le {ts})\n")
    print(f"📄 Listing complet sauvegardé dans emails_export.txt")

async def cmd_export():
    """Relit emails.txt et affiche un tableau propre."""
    if not os.path.exists(EMAILS_FILE):
        print("❌ emails.txt vide. Générez des emails d'abord.")
        return
    with open(EMAILS_FILE) as f:
        emails = [l.strip() for l in f if l.strip()]
    print(f"\n{'─'*50}")
    print(f"  📧  {len(emails)} emails dans emails.txt")
    print(f"{'─'*50}")
    for i, e in enumerate(emails, 1):
        print(f"  {i:>3}.  {e}")
    print(f"{'─'*50}\n")

# ─────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────
CMDS = {
    "login":    (cmd_login,    False),
    "generate": (cmd_generate, True),
    "list":     (cmd_list,     True),
    "export":   (cmd_export,   True),
}

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "export"
    if cmd not in CMDS:
        print(__doc__)
        sys.exit(0)
    fn, is_async = CMDS[cmd]
    if is_async:
        asyncio.run(fn())
    else:
        fn()
