#!/usr/bin/env python3
"""
GrabDiscount — Générateur d'emails iCloud Hide My Email
========================================================
Usage:
  python3 run.py login     → Ouvre Chrome pour se connecter à iCloud
  python3 run.py generate  → Génère des emails (demande combien)
  python3 run.py list      → Liste tous les emails générés
  python3 run.py export    → Exporte emails.txt en tableau propre
"""

from __future__ import annotations
import asyncio, os, sys, json, time, datetime, re
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)
COOKIE_FILE  = os.path.join(BASE_DIR, "cookie.txt")
EMAILS_FILE  = os.path.join(BASE_DIR, "emails.txt")
EXPORT_FILE  = os.path.join(BASE_DIR, "emails_export.txt")

EDIT_COOKIE_HEADER = """// Semicolon separated Cookie File\n// This file was generated by EditThisCookie"""

# ─────────────────────────────────────────
#  SELENIUM — LOGIN + COOKIE EXTRACTION
# ─────────────────────────────────────────
PROFILE_DIR  = os.path.join(BASE_DIR, "chrome_selenium_profile")
DEBUG_PORT   = 9222   # fixed remote-debugging port so we can always reconnect

def _kill_existing_chrome():
    """Kill any Chrome-for-Testing using our profile directory."""
    import subprocess
    try:
        result = subprocess.run(
            ["pgrep", "-f", "chrome_selenium_profile"],
            capture_output=True, text=True
        )
        for pid in result.stdout.strip().splitlines():
            try:
                os.kill(int(pid), 9)
            except (ValueError, ProcessLookupError):
                pass
        if result.stdout.strip():
            time.sleep(1)   # wait for Chrome to fully release the profile lock
    except Exception:
        pass

def _open_chrome():
    """Launch Chrome with a fixed debug port; returns the subprocess."""
    import subprocess, glob as _glob
    # Find chromedriver / chrome-for-testing binary
    chrome_bin = None
    patterns = [
        os.path.expanduser("~/.cache/selenium/chrome/mac-arm64/*/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"),
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    ]
    for pat in patterns:
        found = sorted(_glob.glob(pat), reverse=True)
        if found:
            chrome_bin = found[0]
            break
    if not chrome_bin:
        raise RuntimeError("Chrome binary introuvable.")

    cmd = [
        chrome_bin,
        f"--user-data-dir={PROFILE_DIR}",
        f"--remote-debugging-port={DEBUG_PORT}",
        "--remote-allow-origins=*",
        "--no-first-run",
        "--disable-default-apps",
        "--disable-sync",
        "https://www.icloud.com/settings/",
    ]
    return subprocess.Popen(cmd)

def _cdp_get_icloud_cookies() -> list[dict]:
    """Connect to Chrome CDP and return all iCloud cookies."""
    import urllib.request, json, websocket as ws_lib

    try:
        with urllib.request.urlopen(f"http://localhost:{DEBUG_PORT}/json", timeout=5) as r:
            tabs = json.loads(r.read())
    except Exception:
        return []

    ws_url = None
    for t in tabs:
        if t.get("webSocketDebuggerUrl"):
            ws_url = t["webSocketDebuggerUrl"]
            break
    if not ws_url:
        return []

    result = []
    try:
        ws = ws_lib.create_connection(ws_url, timeout=5)
        ws.send(json.dumps({"id": 1, "method": "Network.getAllCookies"}))
        for _ in range(10):
            msg = json.loads(ws.recv())
            if msg.get("id") == 1:
                all_cookies = msg.get("result", {}).get("cookies", [])
                result = [c for c in all_cookies
                          if "icloud" in c.get("domain","").lower()
                          or "apple" in c.get("domain","").lower()]
                break
        ws.close()
    except Exception:
        pass
    return result

def _save_cookies(cookies: list[dict]):
    """Save cookie list → cookie.txt in HTTP Cookie header format."""
    parts = [f'{c["name"]}={c["value"]}' for c in cookies]
    line = "; ".join(parts)
    with open(COOKIE_FILE, "w", encoding="utf-8") as f:
        f.write(EDIT_COOKIE_HEADER + "\n" + line)

def cmd_login():
    """Ouvre Chrome sur iCloud.com, attend la connexion, extrait les cookies automatiquement."""
    _kill_existing_chrome()
    print("\n🌐 Ouverture de Chrome…\n   → Connectez-vous à iCloud.com dans la fenêtre qui s'ouvre.")
    print("   → Le script détectera automatiquement votre connexion (max 3 min).\n")

    proc = _open_chrome()
    deadline = time.time() + 180  # 3 minutes
    last_count = 0

    while time.time() < deadline:
        time.sleep(3)
        cookies = _cdp_get_icloud_cookies()
        session_ok = any(c["name"] == "X-APPLE-DS-WEB-SESSION-TOKEN" for c in cookies)
        if session_ok and len(cookies) != last_count:
            last_count = len(cookies)
            print(f"  ⏳ {len(cookies)} cookies iCloud détectés… vérification session…")
            # Give the page 2 more seconds to finish loading all cookies
            time.sleep(2)
            cookies = _cdp_get_icloud_cookies()
            _save_cookies(cookies)
            print(f"\n✅ {len(cookies)} cookies sauvegardés dans cookie.txt !")
            print("   Vous pouvez maintenant lancer : python3 run.py generate\n")
            return

    proc.terminate()
    print("❌ Délai dépassé. Relancez la commande et connectez-vous rapidement.")

# ─────────────────────────────────────────
#  iCLOUD API
# ─────────────────────────────────────────
def load_cookies() -> str:
    if not os.path.exists(COOKIE_FILE):
        print("❌ cookie.txt introuvable. Lancez d'abord : python3 run.py login")
        sys.exit(1)
    with open(COOKIE_FILE, "r") as f:
        lines = [l for l in f.read().splitlines() if not l.startswith("//") and l.strip()]
    if not lines:
        print("❌ cookie.txt vide. Lancez d'abord : python3 run.py login")
        sys.exit(1)
    return lines[0]

import aiohttp, ssl, certifi

class ICloudHME:
    base_v1 = "https://p68-maildomainws.icloud.com/v1/hme"
    base_v2 = "https://p68-maildomainws.icloud.com/v2/hme"
    # Build number and dsid are patched dynamically from the cookie
    params   = {"clientBuildNumber":"2612Build21","clientMasteringNumber":"2612Build21","clientId":"","dsid":""}

    def __init__(self, cookies: str):
        self.cookies = cookies.strip()
        # Auto-extract dsid from X-APPLE-WEBAUTH-USER cookie value
        import re as _re
        m = _re.search(r'd=(\d+)', self.cookies)
        if m:
            self.__class__.params = dict(self.params, dsid=m.group(1))

    async def __aenter__(self):
        ssl_ctx   = ssl.create_default_context(cafile=certifi.where())
        connector = aiohttp.TCPConnector(ssl=ssl_ctx)
        self.session = aiohttp.ClientSession(
            headers={
                "User-Agent":    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/123 Safari/537.36",
                "Content-Type":  "text/plain",
                "Accept":        "*/*",
                "Origin":        "https://www.icloud.com",
                "Referer":       "https://www.icloud.com/",
                "Cookie":        self.cookies,
            },
            timeout=aiohttp.ClientTimeout(total=15),
            connector=connector,
        )
        return self

    async def __aexit__(self, *_):
        await self.session.close()

    async def generate_one(self) -> str | None:
        try:
            async with self.session.post(f"{self.base_v1}/generate", params=self.params, json={"langCode":"en-us"}) as r:
                data = await r.json()
        except Exception as e:
            print(f"  ⚠ generate error: {e}")
            return None
        if not isinstance(data, dict) or not data.get("success"):
            err = data.get("error") if isinstance(data, dict) else data
            reason = (err if isinstance(err, str) else
                      (err or {}).get("errorMessage") if isinstance(err, dict) else str(err))
            reason = reason or (data.get("reason","?") if isinstance(data, dict) else "?")
            print(f"  ⚠ generate failed: {reason}")
            return None
        email = data["result"]["hme"]
        # Reserve
        try:
            async with self.session.post(f"{self.base_v1}/reserve", params=self.params,
                json={"hme": email, "label": "GrabDiscount", "note": "Auto-generated"}) as r:
                res = await r.json()
        except Exception as e:
            print(f"  ⚠ reserve error for {email}: {e}")
            return None
        if not isinstance(res, dict) or not res.get("success"):
            err = res.get("error") if isinstance(res, dict) else res
            reason = (err if isinstance(err, str) else
                      (err or {}).get("errorMessage") if isinstance(err, dict) else str(err))
            reason = reason or (res.get("reason","?") if isinstance(res, dict) else "?")
            print(f"  ⚠ reserve failed for {email}: {reason}")
            return None
        return email

    async def generate_batch(self, n: int) -> list[str]:
        results = await asyncio.gather(*[self.generate_one() for _ in range(min(n,10))])
        return [r for r in results if r]

    async def list_all(self) -> list[dict]:
        try:
            async with self.session.get(f"{self.base_v2}/list", params=self.params) as r:
                data = await r.json()
        except Exception as e:
            print(f"  ⚠ list error: {e}")
            return []
        if not data.get("success"):
            print(f"  ⚠ list failed: {data}")
            return []
        return data.get("result", {}).get("hmeEmails", [])

# ─────────────────────────────────────────
#  COMMANDES
# ─────────────────────────────────────────
async def cmd_generate():
    cookies = load_cookies()
    # Accepte le count depuis sys.argv[2] (ex: python3 run.py generate 5)
    # Sinon demande interactivement
    if len(sys.argv) > 2:
        try:
            n = int(sys.argv[2])
            print(f"\n📧 Génération de {n} email(s)...")
        except ValueError:
            n = 5
    else:
        try:
            n = int(input("\n📧 Combien d'emails à générer ? (max 25 recommandé) : ").strip())
        except (ValueError, EOFError):
            n = 5

    all_emails = []
    async with ICloudHME(cookies) as hme:
        generated = 0
        while generated < n:
            batch = min(n - generated, 10)
            print(f"\n  Génération batch {generated+1}–{generated+batch}...")
            emails = await hme.generate_batch(batch)
            for e in emails:
                print(f"  ✅ {e}")
            all_emails.extend(emails)
            generated += batch
            if generated < n:
                print(f"  ⏳ Pause 5s (limite API Apple)...")
                await asyncio.sleep(5)

    if all_emails:
        with open(EMAILS_FILE, "a", encoding="utf-8") as f:
            f.write("\n".join(all_emails) + "\n")
        print(f"\n✅ {len(all_emails)} emails sauvegardés dans emails.txt")
    else:
        print("\n❌ Aucun email généré. Vérifiez cookie.txt (relancez : python3 run.py login)")

async def cmd_list():
    cookies = load_cookies()
    async with ICloudHME(cookies) as hme:
        emails = await hme.list_all()

    if not emails:
        print("Aucun email trouvé (ou session expirée).")
        return

    active   = [e for e in emails if e.get("isActive")]
    inactive = [e for e in emails if not e.get("isActive")]

    print(f"\n{'─'*62}")
    print(f"  📧  {len(active)} emails actifs   |   {len(inactive)} désactivés")
    print(f"{'─'*62}")
    print(f"  {'EMAIL':<38} {'CRÉÉ LE':<18}")
    print(f"{'─'*62}")
    for e in active:
        ts = datetime.datetime.fromtimestamp(e.get("createTimestamp",0)/1000).strftime("%d/%m/%Y %H:%M")
        print(f"  {e['hme']:<38} {ts}")
    print(f"{'─'*62}\n")

    # Sauvegarde aussi dans emails_export.txt
    with open(EXPORT_FILE, "w", encoding="utf-8") as f:
        f.write(f"# Export iCloud Hide My Email — {datetime.datetime.now():%d/%m/%Y %H:%M}\n")
        f.write(f"# {len(active)} emails actifs\n\n")
        for e in active:
            ts = datetime.datetime.fromtimestamp(e.get("createTimestamp",0)/1000).strftime("%d/%m/%Y %H:%M")
            f.write(f"{e['hme']}  (créé le {ts})\n")
    print(f"📄 Listing complet sauvegardé dans emails_export.txt")

async def cmd_export():
    """Relit emails.txt et affiche un tableau propre."""
    if not os.path.exists(EMAILS_FILE):
        print("❌ emails.txt vide. Générez des emails d'abord.")
        return
    with open(EMAILS_FILE) as f:
        emails = [l.strip() for l in f if l.strip()]
    print(f"\n{'─'*50}")
    print(f"  📧  {len(emails)} emails dans emails.txt")
    print(f"{'─'*50}")
    for i, e in enumerate(emails, 1):
        print(f"  {i:>3}.  {e}")
    print(f"{'─'*50}\n")

# ─────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────
CMDS = {
    "login":    (cmd_login,    False),
    "generate": (cmd_generate, True),
    "list":     (cmd_list,     True),
    "export":   (cmd_export,   True),
}

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "export"
    if cmd not in CMDS:
        print(__doc__)
        sys.exit(0)
    fn, is_async = CMDS[cmd]
    if is_async:
        asyncio.run(fn())
    else:
        fn()
